export const snacks = [
  "smulrol",
  "sitostick",
  "chickenwings",
  "vlammetjes",
  "shoarmarol",
  "berenklauw",
  "pikanto",
  "falafel",
  "gehaktbal",
  "bamischijf",
  "nasibal",
  "kaassoufflé",
  "hamkaassoufflé",
  "bitterballen",
  "kipcorn",
  "mexicano",
  "kipsaté",
  "kipnuggets",
  "hamburger",
  "cheeseburger",
  "kroket",
  "loempia",
  "frikandel",
  "schnitzel",
  "lekkerbek",
  "viandel",
  "smulrol",
  // no support yet for adjectives before words ending on -tje
  // "lihanboutje",
  "pikanto",
  "sjaslick",
  "braadworst",
  "groentekroket",
];

export const fictionalSnacks = [
  "kadaverstaaf",
];
